name: Push to RAINBOW

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - '**.jsonld'
      - '**.schema.yml'
      - .github/workflows/push-to-rainbow.yml

jobs:
  uplift:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/opengeospatial/ogc-na-tools.git check-jsonschema
      - name: Process files
        env:
          DB_USERNAME: ${{ secrets.UPLOAD_GRAPH_STORE_USERNAME }}
          DB_PASSWORD: ${{ secrets.UPLOAD_GRAPH_STORE_PASSWORD }}
        run: |
          python -m check_jsonschema -v --schemafile ebv-iadopt.schema.yml ebv-iadopt.jsonld
          python -m ogc.na.update_vocabs .ogc/catalog.ttl --batch  -w . \
            --update --graph-store https://defs-dev.opengis.net/fuseki-hosted/data
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'entailed/'
